# Generated by Django 3.0.8 on 2021-01-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=10)),
                ('pub_date', models.DateField()),
                ('slug', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='shop/images')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('slug', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='discountedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.CharField(default='', max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('discountPercentage', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('presentPrice', models.FloatField(null=True)),
                ('pub_date', models.DateField()),
                ('slug', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='shop/images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('price', models.FloatField(null=True)),
                ('presentPrice', models.FloatField(null=True)),
                ('discount', models.FloatField(null=True)),
                ('pub_date', models.DateField()),
                ('slug', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='shop/images')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_details', models.CharField(max_length=99999999999999)),
                ('customerUsername', models.CharField(max_length=1000)),
                ('totalPrice', models.CharField(max_length=1000)),
                ('discount', models.CharField(max_length=1000)),
                ('dates', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('slug', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('no_of_orders', models.CharField(max_length=100)),
            ],
        ),
    ]
