# Generated by Django 3.0.8 on 2021-02-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('caption', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='shop/images')),
                ('discountPercentage', models.FloatField(null=True)),
            ],
        ),
    ]
