# Generated by Django 3.0.8 on 2021-02-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210211_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountedproducts',
            name='sellingFrequency',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='sellingFrequency',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
