# Generated by Django 3.0.8 on 2021-02-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210212_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountedproducts',
            options={'ordering': ['sellingFrequency']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sellingFrequency']},
        ),
        migrations.AlterField(
            model_name='discountedproducts',
            name='sellingFrequency',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='sellingFrequency',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
